### ISSUE TITLE
Running the test on my own BERT model

### ISSUE THREAD

**Issue by abhi060698** [IKMLab/arct2#1]
Hey,
Thank you so much for this repo. How do I run the experiment on a BERT model that I have pretrained myself? 
Thanks

**Comment by timniven** [comment]
Hi there,

Create a new file in the `experiments` directory, say `my_experiment.py`. Copy the code from an experimental setup, say BERT large on the adversarial dataset, and put your model constructor in there:

```
"""Experiment for MY_MODEL on the adversarial dataset."""
from arct import bert
from util import training, experiments


def run():
    args = training.Args(  # CHANGE THESE TO SUIT YOU
        experiment_name=__name__.split('.')[-1],
        bert_model='bert-large-uncased',
        annealing_factor=0.1,
        num_train_epochs=20,
        max_seq_length=80,
        learning_rate=2e-5)
    model_constructor = bert.BERT.from_args  # PUT YOUR CONSTRUCTOR HERE
    data_loaders = bert.DataLoadersAdv(args)
    experiments.run(
        args=args,
        model_constructor=model_constructor,
        data_loaders=data_loaders,
        grid_space=None,  # ADD A GRID SPACE HERE IF YOU WANT
        n_experiments=20,
        do_grid=False)
```

If you wanted to do a grid search, in `experiments.run` add a keyword argument `grid_space={...your grid space here...}`. Obviously change the `training.Args` to suit your situation.

The model constructor needs to take the `training.Args`. When the experiment is run, it will be instantiated with

`model = model_constructor(args)`

If you hook all that up then you can execute

`python run.py my_experiment`
